### ISSUE TITLE
Calibre Mac OS X

### ISSUE THREAD

**Issue by nivaca** [Arkq/calibre-latex#1]
Hi,
I've been trying to make your script work in Mac OS X, but the directory `/usr/lib64/calibre/calibre/ebooks/conversion/plugins/`doesn't exist. The file `builtins.py` doesn't exist either.
I would really like to give a try to your plugin. 
Many thanks.
Nicolas Vaughan

**Comment by arkq** [comment]
Hi,

I'm afraid, that it is not possible to simply "monkey-patch" Calibre on
Mac OS X. The dmg package contains Mach executables, not raw python
source files.

If you really want to give a try this plugin, you have to run in on
Linux or at least run it from the source code itself (after "applying"
this plugin). I'm not a OS X user, though, so I might be wrong...

Try this guide:
https://manual.calibre-ebook.com/develop.html#os-x-development-environment

Best Regards,
Arek

**Comment by nivaca** [comment]
Hi Arkq, I tried it also on my Linux machine, but it also lacks those directories/files. Is it perhaps because newer versions of Calibre don't contain them? Thanks. Nicolas

On Wed, Jun 22, 2016 at 03:12, Arkadiusz Bokowy notifications@github.com wrote:
Hi,

I'm afraid, that it is not possible to simply "monkey-patch" Calibre on
Mac OS X. The dmg package contains Mach executables, not raw python
source files.

If you really want to give a try this plugin, you have to run in on
Linux or at least run it from the source code itself (after "applying"
this plugin). I'm not a OS X user, though, so I might be wrong...

Try this guide:
https://manual.calibre-ebook.com/develop.html#os-x-development-environment

Best Regards,
Arek

**Comment by arkq** [comment]
I've checked, and it seems, that in the newest version of Calibre, all those directories/files exist:
https://github.com/kovidgoyal/calibre/tree/master/src/calibre/ebooks/conversion/plugins/
https://github.com/kovidgoyal/calibre/blob/master/src/calibre/customize/builtins.py

But I might miss something from the big picture, because I'm currently using Calibre version 1.20, which is kinda old :/

Could you send the exact version of Calibre and the Linux distribution you've been trying to use? Please note, that the installation guide assumes, that one is using 64 bit version of Linux.

**Comment by nivaca** [comment]
OK, thanks.

I'm using Ubuntu 14.04 64 bits.

My Calibre version is 2.59.

Cheers,

Nicolas

**Comment by arkq** [comment]
OK, so I gather, that you've installed Calibre not from Ubuntu's package repository, but from Calibre homepage, using provided instruction: https://calibre-ebook.com/download_linux Then, you have had to select the installation directory, which is most likely /opt (it could have been anything, though).

From this point, things got a little bit more complicated. The source code, which is provided by this way of installation is "precompiled" (*.pyo files). Buuuuutt, it is possible (theoretically) to patch the source anyway.

Wherever you've installed Calibre, try to find the directory "lib/python2.7/site-packages/calibre/". This is the location of the source code (mangled, though). Then, place the tex_outpu.py plugin file in the plugins location, e.g.: /opt/calibre/lib/python2.7/site-packages/calibre/ebooks/conversion/plugins/. Next step is to register this plugin.... Copy, [this file](https://github.com/kovidgoyal/calibre/blob/v2.59.0/src/calibre/customize/builtins.py) into the lib/python2.7/site-packages/calibre/customize/ directory, and apply the patch (add to the end of the file):

```
from calibre.ebooks.conversion.plugins.tex_output import LatexOutput
plugins += [LatexOutput]
```

And that's all. Everything should work flawlessly. I will check this out tomorrow and if it works, I will update the installation instruction.

If my guessing is not correct, please tell me exactly how you've installed Calibre.

**Comment by nivaca** [comment]
I did everything you said. However, I get the following error message:

```
Traceback (most recent call last):
  File "site.py", line 66, in main
  File "site-packages/calibre/gui_launch.py", line 63, in calibre
  File "site-packages/calibre/gui2/main.py", line 525, in main
  File "site-packages/calibre/gui2/main.py", line 371, in run_gui
  File "site-packages/calibre/gui2/ui.py", line 28, in <module>
  File "site-packages/calibre/db/legacy.py", line 19, in <module>
  File "site-packages/calibre/db/cache.py", line 18, in <module>
  File "site-packages/calibre/customize/ui.py", line 17, in <module>
  File "/opt/calibre/lib/python2.7/site-packages/calibre/customize/builtins.py", line 1858, in <module>
    from calibre.ebooks.conversion.plugins.tex_output import LatexOutput
ImportError: No module named tex_output
```

I installed Calibre with the official installer from the website.

**Comment by nivaca** [comment]
Sorry. Just checked I made a mistake. It's working now!
A question: would this also work on a Mac installation of Calibre?

**Comment by arkq** [comment]
I'm glad, that my guessing was right. As for Mac, I'm not sure, I will have to check, how the source code is delivered in the installation package. If Mac installation contains *.pyo files, this recipe should work for Mac as well. But Mac installation package is like CD image, and it might not be possible to modify it :/ You might give it a try, though :)

**Comment by nivaca** [comment]
It also works on a Mac. Cheers!
On Wed, Jun 22, 2016 at 16:07, Arkadiusz Bokowy notifications@github.com wrote:
OK, so I gather, that you've installed Calibre not from Ubuntu's package repository, but from Calibre homepage, using provided instruction: https://calibre-ebook.com/download_linux [https://calibre-ebook.com/download_linux] Then, you have had to select the installation directory, which is most likely /opt (it could have been anything, though).

From this point, things got a little bit more complicated. The source code, which is provided by this way of installation is "precompiled" (*.pyo files). Buuuuutt, it is possible (theoretically) to patch the source anyway.

Wherever you've installed Calibre, try to find the directory "lib/python2.7/site-packages/calibre/". This is the location of the source code (mangled, though). Then, place the tex_outpu.py plugin file in the plugins location, e.g.: /opt/calibre/lib/python2.7/site-packages/calibre/ebooks/conversion/plugins/. Next step is to register this plugin.... Copy, this file [https://github.com/kovidgoyal/calibre/blob/v2.59.0/src/calibre/customize/builtins.py] into the lib/python2.7/site-packages/calibre/customize/ directory, and apply the patch (add to the end of the file):

from calibre.ebooks.conversion.plugins.tex_output import LatexOutput
plugins += [LatexOutput]

And that's all. Everything should work flawlessly. I will check this out tomorrow and if it works, I will update the installation instruction.

If my guessing is not correct, please tell me exactly how you've installed Calibre.
